# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=256)),
                ('loginPchallenge', models.CharField(max_length=256)),
                ('created', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
