# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='loginPchallenge',
            new_name='login_challenge',
        ),
    ]
